#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Every workflow and composite action, publish-external.yml, and the setup-tool
# actions, read as text.
# A part of packaging_ci_test.sh, a suite of its own so the Windows shards split them.
# The preamble's source line is packaging_ci_test.sh's - it sources the harness, and
# holds the helpers the parts share (GLOSSARY: HI.34).
#
# GLOSSARY: HI.30 + HI.34
# shellcheck disable=SC2329,SC2031
set -euo pipefail

_HI_PACKAGING_CI_PART=workflows
# shellcheck source=./packaging_ci_test.sh
source "${BASH_SOURCE[0]%/*}/packaging_ci_test.sh"

# aur's own guard, in publish-external.yml: no release.event to read a tag
# from (this is a workflow_dispatch, not a push), so it is the same skip
# spelled off the tag input instead
function test_prerelease_tags_reach_no_external_channel() {
  [ -f "$_HI_PUBLISH_EXTERNAL_WF" ] || return 0
  local job guard="!contains(github.event.inputs.tag, '-')"
  job="$(_hi_wf_job "$_HI_PUBLISH_EXTERNAL_WF" aur)"
  [[ "$job" == *"$guard"* ]] || {
    _hi_cecho " | publish-external.yml's aur job runs on a prerelease tag" "$RED"
    return 1
  }
}

# aur does not run off a tag push at all - a v0.0.x/prerelease skip on
# `github.ref_name` alone, with no workflow_dispatch guard beside it, would
# read as "still automatic" and silently reintroduce the coupling this split
# exists to remove. The tap is release.yml's (below), not this file's.
function test_aur_is_dispatch_only() {
  [ -f "$_HI_PUBLISH_EXTERNAL_WF" ] || return 0
  { grep -qE '^ *workflow_dispatch:' "$_HI_PUBLISH_EXTERNAL_WF" &&
    ! grep -qE '^ *(push|pull_request):' "$_HI_PUBLISH_EXTERNAL_WF" &&
    ! grep -q "^  tap:" "$_HI_PUBLISH_EXTERNAL_WF" &&
    ! grep -q "^  aur:" "$_HI_RELEASE_WF"; } || _hi_why _HI_PUBLISH_EXTERNAL_WF _HI_RELEASE_WF
}

# The tap PR is part of the release: release.yml's tap job waits on brew's
# verdict (a formula that failed install/test/audit never reaches the tap),
# skips the same debug and prerelease tags brew does, opens a PR rather than
# pushing, and reads the tap token - never the repo's own - for that.
function test_release_workflow_opens_the_tap_pr_after_brew() {
  local job
  job="$(_hi_wf_job "$_HI_RELEASE_WF" tap)"
  [ -n "$job" ] || {
    _hi_cecho " | release.yml has no tap job" "$RED"
    return 1
  }
  [[ "$job" == *"needs: brew"* ]] &&
    [[ "$job" == *"needs.brew.result == 'success'"* ]] &&
    [[ "$job" == *"needs.brew.outputs.debug != 'true'"* ]] &&
    [[ "$job" == *"needs.brew.outputs.prerelease != 'true'"* ]] &&
    [[ "$job" == *"secrets.HOMEBREW_TAP_TOKEN"* ]] &&
    [[ "$job" == *"gh pr create"* ]] &&
    [[ "$job" == *"tap_formula.sh <../dist/manifests/say-hi.rb >Formula/say-hi.rb"* ]] &&
    [[ "$job" != *"- [ ]"* ]] &&
    [[ "$job" != *"environment:"* ]] || _hi_why job
}

# The tap's copy of the formula: the template's header (this repository's
# v0.0.0/bump.sh warning) swapped for the tap's three lines, everything from
# the bare `#` down byte-for-byte the template - and a formula with no bare
# `#` above its class refused rather than emptied.
function test_tap_formula_swaps_only_the_template_header() {
  local script="$_HI_ROOT/.github/scripts/tap_formula.sh" out want
  [ -f "$script" ] || return 0 # a shipped tree has no .github
  out="$(bash "$script" <"$_HI_FORMULA")" || _hi_why script _HI_FORMULA || return 1
  want="# Generated by say-hi's release workflow from packaging/homebrew/say-hi.rb
# in https://github.com/ivylikethevine/say-hi. Edit it there, not here.
# Pull requests to this tap are opened automatically for each release.
$(sed -n '/^#$/,$p' "$_HI_FORMULA")"
  [ "$out" = "$want" ] || {
    _hi_cecho " | tap_formula.sh's output is not the template under the tap header" "$RED"
    return 1
  }
  [[ "$out" != *"v0.0.0 sentinel"* ]] || _hi_why out || return 1
  ! printf 'x\nclass SayHi < Formula\n#\n' | bash "$script" >/dev/null 2>&1 || _hi_why script
}

# The release page says where the formula went and shows the thing running:
# publish lays out a `tap` and a `demo` slot and dispatches demos.yml at the
# tag; the tap job links its PR into one and demos.yml's attach job embeds the
# uploaded GIF in the other, each under the GITHUB_TOKEN with contents: write
# and in the one concurrency group, so the two writers never interleave. No
# tag trigger of demos.yml's own: that run would race the release it attaches to.
function test_release_body_links_the_tap_pr_and_embeds_the_demo() {
  # shellcheck disable=SC2016 # the workflows' own literals, expanded there
  local publish tap attach group='group: release-body-${{ github.ref_name }}'
  publish="$(_hi_wf_job "$_HI_RELEASE_WF" publish)"
  tap="$(_hi_wf_job "$_HI_RELEASE_WF" tap)"
  attach="$(_hi_wf_job "$_HI_DEMOS_WF" attach)"
  [[ "$publish" == *'"<!-- hi:demo -->"'* && "$publish" == *'"<!-- hi:tap -->"'* ]] || _hi_why publish || return 1
  # shellcheck disable=SC2016 # likewise
  [[ "$publish" == *'gh_dispatch.sh demos.yml "$GITHUB_REF_NAME"'* ]] || _hi_why publish || return 1
  # shellcheck disable=SC2016 # likewise
  [[ "$tap" == *'release_slot.sh "$GITHUB_REPOSITORY" "$TAG" tap'* && "$tap" == *"contents: write"* &&
    "$tap" == *"$group"* && "$tap" == *"GH_TOKEN: \${{ github.token }}"* &&
    "$tap" == *"RELEASE_SLOT_PREFIX: hi"* ]] || _hi_why tap group || return 1
  # shellcheck disable=SC2016 # likewise
  [[ "$attach" == *"github.ref_type == 'tag'"* && "$attach" == *"needs.collect.result == 'success'"* &&
    "$attach" == *'release_slot.sh "$GITHUB_REPOSITORY" "$TAG" demo'* &&
    "$attach" == *'_ci_upload_assets "$TAG" "$RUNNER_TEMP/demo.gif"'* &&
    "$attach" == *'releases/download/$TAG/demo.gif'* && "$attach" == *"contents: write"* &&
    "$attach" == *"$group"* && "$attach" == *"RELEASE_SLOT_PREFIX: hi"* ]] || _hi_why attach group || return 1
  ! sed -n '/^on:/,/^[a-z]/p' "$_HI_DEMOS_WF" | grep -qE '^  push:' || _hi_why _HI_DEMOS_WF
}

# RELEASE_SLOT_PREFIX as both workflow writers set it, to match publish's
# `<!-- hi:... -->` markers
function _hi_release_slot() {
  RELEASE_SLOT_PREFIX=hi bash "$_HI_ROOT/.github/scripts/release_slot.sh" "$@"
}

# a fill replaces its own marker's line and keeps the marker (so a re-run
# replaces it again), leaves the other slot alone, and appends to a body that
# has no marker at all; the markdown reaches the body verbatim
function test_release_slot_fills_only_its_own_line() {
  local got
  local body=$'badges\n<!-- hi:demo -->\n- apk\n<!-- hi:tap -->' once twice
  # shellcheck disable=SC2016 # markdown, not substitution
  once="$(printf '%s\n' "$body" | _hi_release_slot --fill tap '- Homebrew: `brew` ([PR](u1)) \n $x')"
  [ "$once" = $'badges\n<!-- hi:demo -->\n- apk\n- Homebrew: `brew` ([PR](u1)) \\n $x <!-- hi:tap -->' ] || _hi_why once || return 1
  twice="$(printf '%s\n' "$once" | _hi_release_slot --fill tap '- Homebrew: ([PR](u2))')"
  [ "$twice" = $'badges\n<!-- hi:demo -->\n- apk\n- Homebrew: ([PR](u2)) <!-- hi:tap -->' ] || _hi_why twice || return 1
  got="$(printf 'old body\n' | _hi_release_slot --fill demo '![d](g)')"
  [ "$got" = $'old body\n\n![d](g) <!-- hi:demo -->' ] || _hi_why got
}

# the network mode, against a stand-in gh: the body it reads is the body it
# writes back, filled, to the same tag and repo
function test_release_slot_writes_the_body_back_through_gh() {
  local got
  local dir="$_HI_WORKDIR/relslot"
  mkdir -p "$dir/bin"
  cat >"$dir/bin/gh" <<'EOF'
#!/usr/bin/env bash
case "$1 $2 $3 $4 $5" in
"release view v1.2.3 --repo o/r") printf 'top\n<!-- hi:demo -->\nend\n' ;;
"release edit v1.2.3 --repo o/r") cp "$7" "$HI_SLOT_OUT" ;;
*) exit 1 ;;
esac
EOF
  chmod +x "$dir/bin/gh"
  HI_SLOT_OUT="$dir/out" PATH="$dir/bin:$PATH" _hi_release_slot o/r v1.2.3 demo '![d](g)' || _hi_why dir || return 1
  got="$(cat "$dir/out")"
  [ "$got" = $'top\n![d](g) <!-- hi:demo -->\nend' ] || _hi_why got dir
}

# gh_asset.sh against a stand-in gh: the first upload is refused the way
# GitHub refused v0.4.3's rpm, and the asset still has to land. The name is
# cleared by asset id first - an attempt refused part way can still hold it,
# and --clobber deletes only what the release's own asset list admits to -
# and then the raw uploads.github.com POST goes out as octet-stream, the one
# half `gh release upload` cannot be talked into: it sends application/x-rpm
# for that extension off a hardcoded table. `sleep` is stubbed too; the
# retry's own five seconds are not this suite's to spend.
function test_gh_asset_retries_through_the_raw_endpoint() {
  local dir="$_HI_WORKDIR/ghasset" out rc=0
  rm -rf "$dir"
  mkdir -p "$dir/bin"
  cat >"$dir/bin/gh" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >>"$CI_GH_LOG"
case "$*" in
*releases/tags/v9.9.9*) printf '4242\t77\n' ;;
*"--method DELETE"*) ;;
*"release upload"*)
  echo "HTTP 500: Error saving asset" >&2
  exit 1
  ;;
*uploads.github.com*) printf '{"state":"uploaded"}\n' ;;
*) exit 1 ;;
esac
EOF
  printf '#!/usr/bin/env bash\nexit 0\n' >"$dir/bin/sleep"
  chmod +x "$dir/bin/gh" "$dir/bin/sleep"
  : >"$dir/pkg.rpm"
  out="$(
    # shellcheck source=../../.github/scripts/gh_asset.sh
    source "$_HI_ROOT/.github/scripts/gh_asset.sh"
    PATH="$dir/bin:$PATH" GITHUB_REPOSITORY=o/r CI_GH_LOG="$dir/log" \
      _ci_upload_assets v9.9.9 "$dir/pkg.rpm" 2>&1
  )" || rc=$?
  [ "$rc" = 0 ] || {
    _hi_cecho " | gh_asset.sh gave up on a file the fallback could have landed: [$out]" "$RED"
    return 1
  }
  { grep -qF 'releases/assets/77' "$dir/log" &&
    grep -qF -- '--method DELETE' "$dir/log" &&
    grep -qF 'https://uploads.github.com/repos/o/r/releases/4242/assets?name=pkg.rpm' "$dir/log" &&
    grep -qF 'Content-Type: application/octet-stream' "$dir/log"; } || _hi_why dir
}

# ...and the list is finished whatever any one file does. Three assets, the
# middle one refused every way there is: the other two still attach, the step
# still fails, and the annotation names the missing one once at the end -
# rather than an error about the rpm and silence about what was behind it,
# which is how v0.4.3 shipped without its signature, SBOM and provenance.
function test_gh_asset_attaches_the_rest_and_names_the_missing() {
  local dir="$_HI_WORKDIR/ghasset-partial" out rc=0
  rm -rf "$dir"
  mkdir -p "$dir/bin"
  cat >"$dir/bin/gh" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >>"$CI_GH_LOG"
case "$*" in
*bad.rpm*) exit 1 ;;
*releases/tags/v9.9.9*) printf '4242\t\n' ;;
*"--method DELETE"*) ;;
*) printf '{"state":"uploaded"}\n' ;;
esac
EOF
  printf '#!/usr/bin/env bash\nexit 0\n' >"$dir/bin/sleep"
  chmod +x "$dir/bin/gh" "$dir/bin/sleep"
  : >"$dir/a.deb"
  : >"$dir/bad.rpm"
  : >"$dir/c.apk"
  out="$(
    # shellcheck source=../../.github/scripts/gh_asset.sh
    source "$_HI_ROOT/.github/scripts/gh_asset.sh"
    PATH="$dir/bin:$PATH" GITHUB_REPOSITORY=o/r CI_GH_LOG="$dir/log" \
      _ci_upload_assets v9.9.9 "$dir/a.deb" "$dir/bad.rpm" "$dir/c.apk" 2>&1
  )" || rc=$?
  [ "$rc" -ne 0 ] || _hi_why rc || return 1
  [[ "$out" == *"::error title=Release assets::v9.9.9 is missing: bad.rpm"* ]] || {
    _hi_cecho " | gh_asset.sh said: [$out]" "$RED"
    return 1
  }
  # the two either side of it went up anyway - the whole point
  { grep -qF 'a.deb' "$dir/log" && grep -qF 'c.apk' "$dir/log"; } || _hi_why dir
}

# _hi_tool_dir <name> - a scratch home for setup-tool's cases: src/ holds what
# the stand-in curl in bin/ serves by basename (logging each URL asked for),
# out/ is the bin directory, tools.txt the roster. Prints it.
function _hi_tool_dir() {
  local dir="$_HI_WORKDIR/settool-$1"
  mkdir -p "$dir/bin" "$dir/src" "$dir/out"
  : >"$dir/tools.txt"
  cat >"$dir/bin/curl" <<'EOF'
#!/usr/bin/env bash
dest=""
while [ $# -gt 1 ]; do
  [ "$1" != -o ] || dest="$2"
  shift
done
printf '%s\n' "$1" >>"$HI_TOOL_SRC/../urls"
cp "$HI_TOOL_SRC/${1##*/}" "$dest" 2>/dev/null || exit 22
EOF
  chmod +x "$dir/bin/curl"
  printf '%s' "$dir"
}

# _hi_tool_sum <file> - its sha256, by whichever tool this machine has
function _hi_tool_sum() {
  local sum
  sum="$(sha256sum "$1" 2>/dev/null || shasum -a 256 "$1")"
  printf '%s' "${sum%% *}"
}

# _hi_tool_run <dir> <resolve|install> [NAME=VALUE...] - setup-tool's
# install.sh over <dir>, never the default bin directory
function _hi_tool_run() {
  local dir="$1" sub="$2"
  shift 2
  env -u CI_TOOL_VERSION -u CI_TOOL_SHA256 CI_TOOLS_TXT="$dir/tools.txt" CI_TOOL_BIN_DIR="$dir/out" \
    GITHUB_OUTPUT="$dir/output" HI_TOOL_SRC="$dir/src" PATH="$dir/bin:$PATH" "$@" \
    bash "$_HI_ROOT/.github/actions/setup-tool/install.sh" "$sub" 2>&1
}

# setup-tool's lib.sh, the one reader of tools.txt: a row is found by its
# exact name, a sha256 column is one hex for every platform or a list picked
# by platform (the slug defaulting to the platform's name), and a column that
# is neither, or names a platform nobody has, is not well-formed
function test_setup_tool_lib_reads_the_roster() {
  local dir a b got got2 got3
  dir="$(_hi_tool_dir lib)"
  a="$(printf '%064d' 1)" b="$(printf '%064d' 2)"
  printf '%s\n' '# a comment' '' "a.b|1|raw|u||-||$a" "axb|2|raw|u||-||$b" >"$dir/tools.txt"
  (
    # shellcheck source=../../.github/actions/setup-tool/lib.sh
    CI_TOOLS_TXT="$dir/tools.txt" source "$_HI_ROOT/.github/actions/setup-tool/lib.sh"
    got="$(_ci_tool_rows | grep -c .)"
    [ "$got" -eq 2 ] || _hi_because "rows: $(_ci_tool_rows)" || exit 1
    got="$(_ci_tool_row axb)"
    got2="$(_ci_tool_row a.b)"
    [ "$got" = "axb|2|raw|u||-||$b" ] && [ "$got2" = "a.b|1|raw|u||-||$a" ] ||
      _hi_because "a dot in a name matched as a wildcard" || exit 1
    got="$(_ci_tool_row nope 2>&1)"
    { [[ "$got" == "setup-tool: no row for 'nope' in "* ]] && ! _ci_tool_row nope 2>/dev/null; } ||
      _hi_because "an unknown tool" || exit 1
    # one spelling per CPU, whichever uname this is
    case "$(uname -m):$(_ci_platform)" in
    x86_64:*-x86_64 | amd64:*-x86_64 | aarch64:*-aarch64 | arm64:*-aarch64) ;;
    x86_64:* | amd64:* | aarch64:* | arm64:*) _hi_because "platform: $(_ci_platform)" || exit 1 ;;
    esac
    got="$(_ci_sha256_pick "$a" linux-x86_64)"
    got2="$(_ci_sha256_pick "linux-x86_64=$a,darwin-aarch64:arm64=$b" linux-x86_64)"
    got3="$(_ci_sha256_pick "linux-x86_64=$a,darwin-aarch64:arm64=$b" darwin-aarch64)"
    [ "$got" = "$a|" ] && [ "$got2" = "$a|linux-x86_64" ] && [ "$got3" = "$b|arm64" ] ||
      _hi_because "a pick" || exit 1
    ! _ci_sha256_pick "linux-x86_64=$a" darwin-x86_64 2>/dev/null && ! _ci_sha256_pick "" linux-x86_64 2>/dev/null &&
      ! _ci_sha256_pick nothex linux-x86_64 2>/dev/null && ! _ci_sha256_pick "linux-x86_64=nothex" linux-x86_64 2>/dev/null ||
      _hi_because "a pick that should have failed" || exit 1
    _ci_row_sha256_ok "$a" && _ci_row_sha256_ok "linux-aarch64=$a,darwin-x86_64:intel=$b" ||
      _hi_because "a well-formed column was refused" || exit 1
    for col in "${a%?}" "${a%?}G" "plan9-x86_64=$a" "linux-x86_64=$a,linux-aarch64=short"; do
      ! _ci_row_sha256_ok "$col" || _hi_because "took the column $col" || exit 1
    done
  ) || _hi_why col
}

# _hi_tool_build_stubs <dir> - stand-ins for what a source kind reaches for:
# sudo, which logs its words and runs none of them but a mkdir or mv (after
# unlocking <dir>/locked); apt-get, there to be found; make, which builds
# `mk` where ./configure left its mark; cmake, which configures a build
# directory and builds `cm` in it
function _hi_tool_build_stubs() {
  cat >"$1/bin/sudo" <<'EOF'
#!/usr/bin/env bash
printf '%s\n' "$*" >>"$HI_TOOL_SRC/../sudo.log"
case "$1" in mkdir | mv) chmod u+w "$HI_TOOL_SRC/../locked" && "$@" ;; esac
EOF
  printf '#!/bin/sh\nexit 0\n' >"$1/bin/apt-get"
  printf '#!/bin/sh\n[ -f configured ] || exit 0\nprintf "#!/bin/sh\\necho built\\n" >mk && chmod +x mk\n' >"$1/bin/make"
  cat >"$1/bin/cmake" <<'EOF'
#!/usr/bin/env bash
case "$1" in
-S) [ -f "$2/CMakeLists.txt" ] && mkdir -p "$4" ;;
--build) mkdir -p "$2/bin" && printf '#!/bin/sh\necho cmade\n' >"$2/bin/cm" && chmod +x "$2/bin/cm" ;;
esac
EOF
  chmod +x "$1/bin/sudo" "$1/bin/apt-get" "$1/bin/make" "$1/bin/cmake"
}

# the source kinds: the tarball is verified like any download, its build deps
# go to apt by name, and ./configure && make (or cmake) runs in the one
# directory it unpacks to - the built binary is what lands. A tarball with
# no directory, and a build that leaves no tool, each fail by name.
function test_setup_tool_builds_from_a_source_tarball() {
  local dir out rc=0 stage name
  dir="$(_hi_tool_dir build)"
  _hi_tool_build_stubs "$dir"
  stage="$dir/stage"
  mkdir -p "$stage/mk/mk-1.0" "$stage/nomk/nomk-1.0" "$stage/cm/cm-1.0" "$stage/flat"
  printf '#!/bin/sh\n: >configured\n' >"$stage/mk/mk-1.0/configure"
  printf '#!/bin/sh\nexit 0\n' >"$stage/nomk/nomk-1.0/configure"
  chmod +x "$stage/mk/mk-1.0/configure" "$stage/nomk/nomk-1.0/configure"
  printf 'project(cm)\n' >"$stage/cm/cm-1.0/CMakeLists.txt"
  printf 'loose\n' >"$stage/flat/README"
  for name in mk nomk cm flat; do tar -czf "$dir/src/$name.tar.gz" -C "$stage/$name" . || _hi_why dir name stage || return 1; done
  printf '%s\n' "mk|1.0|make:libfoo-dev,libbar-dev|https://x/mk.tar.gz||-||$(_hi_tool_sum "$dir/src/mk.tar.gz")" \
    "nomk|1.0|make|https://x/nomk.tar.gz||-||$(_hi_tool_sum "$dir/src/nomk.tar.gz")" \
    "cm|1.0|cmake:libz-dev|https://x/cm.tar.gz||-||$(_hi_tool_sum "$dir/src/cm.tar.gz")" \
    "flat|1.0|make|https://x/flat.tar.gz||-||$(_hi_tool_sum "$dir/src/flat.tar.gz")" >"$dir/tools.txt"
  out="$(_hi_tool_run "$dir" install CI_TOOL=mk)" || _hi_because "make: $out" || return 1
  [ "${out##*$'\n'}" = built ] && grep -qx 'apt-get install -y --no-install-recommends libfoo-dev libbar-dev' "$dir/sudo.log" &&
    grep -q '^apt-get update' "$dir/sudo.log" || _hi_because "make said [$out], sudo ran: $(cat "$dir/sudo.log")" || return 1
  : >"$dir/sudo.log"
  out="$(_hi_tool_run "$dir" install CI_TOOL=nomk)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"nomk was not built by https://x/nomk.tar.gz"* ]] && [ ! -s "$dir/sudo.log" ] ||
    _hi_because "a build with no tool, rc $rc: $out" || return 1
  out="$(_hi_tool_run "$dir" install CI_TOOL=cm)" || _hi_because "cmake: $out" || return 1
  [ "${out##*$'\n'}" = cmade ] && grep -qx 'apt-get install -y --no-install-recommends build-essential cmake libz-dev' "$dir/sudo.log" ||
    _hi_because "cmake said [$out], sudo ran: $(cat "$dir/sudo.log")" || return 1
  rc=0
  out="$(_hi_tool_run "$dir" install CI_TOOL=flat)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"no source directory inside https://x/flat.tar.gz"* ]] || _hi_because "no directory, rc $rc: $out"
}

# on a machine with no apt-get the build deps are named as assumed present
# and the build goes on: a PATH of this case's stand-ins and a toolbox of
# only what the installer runs, so no apt-get and no sudo can be found
function test_setup_tool_assumes_build_deps_without_apt() {
  local dir out box
  dir="$(_hi_tool_dir noapt)"
  box="$(_hi_real_path settool-box bash sh env dirname grep awk uname mktemp rm cp sha256sum shasum perl \
    mkdir tar gzip find head mv chmod cat sed)"
  printf '#!/bin/sh\n[ -f configured ] || exit 0\nprintf "#!/bin/sh\\necho built\\n" >mk && chmod +x mk\n' >"$dir/bin/make"
  chmod +x "$dir/bin/make"
  mkdir -p "$dir/stage/mk-1.0"
  printf '#!/bin/sh\n: >configured\n' >"$dir/stage/mk-1.0/configure"
  chmod +x "$dir/stage/mk-1.0/configure"
  tar -czf "$dir/src/mk.tar.gz" -C "$dir/stage" . || _hi_why dir || return 1
  printf '%s\n' "mk|1.0|make:libfoo-dev,libbar-dev|https://x/mk.tar.gz||-||$(_hi_tool_sum "$dir/src/mk.tar.gz")" >"$dir/tools.txt"
  out="$(_hi_tool_run "$dir" install CI_TOOL=mk PATH="$dir/bin:$box")" || _hi_because "the build failed: $out" || return 1
  [[ "$out" == *"no apt-get here to install mk's build deps (libfoo-dev libbar-dev) - assuming they are present"* ]] &&
    [ "${out##*$'\n'}" = built ] && [ -x "$dir/out/mk" ] || _hi_because "it said: $out"
}

# a bin directory this user cannot make is made, and the binary moved in,
# through sudo - and only then
function test_setup_tool_reaches_for_sudo_only_for_a_locked_bin_dir() {
  local dir out got
  dir="$(_hi_tool_dir locked)"
  _hi_tool_build_stubs "$dir"
  printf '#!/bin/sh\necho one\n' >"$dir/src/one"
  printf '%s\n' "one|1.0|raw|https://x/one||-||$(_hi_tool_sum "$dir/src/one")" >"$dir/tools.txt"
  out="$(_hi_tool_run "$dir" install CI_TOOL=one)" && [ "$out" = one ] && [ ! -e "$dir/sudo.log" ] ||
    _hi_because "a writable bin dir went through sudo: $out" || return 1
  mkdir -p "$dir/locked"
  chmod 555 "$dir/locked"
  out="$(_hi_tool_run "$dir" install CI_TOOL=one CI_TOOL_BIN_DIR="$dir/locked/bin")"
  chmod 755 "$dir/locked"
  got="$(cut -d' ' -f1 "$dir/sudo.log" | tr '\n' ',')"
  [ "$out" = one ] && [ -x "$dir/locked/bin/one" ] && [ "$got" = "mkdir,mv," ] ||
    _hi_because "said [$out], sudo ran: $(cat "$dir/sudo.log")"
}

# setup-backends' install.sh, every privileged word stood in: podman alone
# comes from ubuntu's own repository, and nomad adds HashiCorp's key and
# list - after the vendor lists are dropped, or the drop would take it out -
# and is asked its version; the cache directory is handed back to the runner
function test_setup_backends_adds_hashicorp_only_for_nomad() {
  local got
  local dir="$_HI_WORKDIR/backends" out drop list
  mkdir -p "$dir/bin"
  # shellcheck disable=SC2016 # the stubs expand these, not this shell
  {
    printf '#!/bin/sh\nprintf "%%s\\n" "$*" >>"$HI_BE_LOG"\n[ "$1" != tee ] || cat >/dev/null\n' >"$dir/bin/sudo"
    printf '#!/bin/sh\nprintf "curl %%s\\n" "$*" >>"$HI_BE_LOG"\necho KEY\n' >"$dir/bin/curl"
    printf '#!/bin/sh\ncat\n' >"$dir/bin/gpg"
    printf '#!/bin/sh\necho noble\n' >"$dir/bin/lsb_release"
    printf '#!/bin/sh\nprintf "nomad %%s\\n" "$*" >>"$HI_BE_LOG"\n' >"$dir/bin/nomad"
  }
  chmod +x "$dir/bin"/*
  out="$(HI_BE_LOG="$dir/podman.log" HI_BACKENDS=podman HI_EXTRA_PACKAGES=uidmap HI_APT_CACHE="$dir/cache" \
    GITHUB_ACTION_PATH="$_HI_ROOT/.github/actions/setup-backends" PATH="$dir/bin:$PATH" \
    bash "$_HI_ROOT/.github/actions/setup-backends/install.sh" 2>&1)" || _hi_because "podman alone failed: $out" || return 1
  [ -d "$dir/cache/partial" ] && grep -qx "apt-get -o Dir::Cache::Archives=$dir/cache install -y podman uidmap" "$dir/podman.log" &&
    grep -qx "rm -rf $dir/cache/partial $dir/cache/lock" "$dir/podman.log" &&
    grep -qx "chown -R $(id -u):$(id -g) $dir/cache" "$dir/podman.log" &&
    ! grep -qE 'hashicorp|^nomad|^curl' "$dir/podman.log" || _hi_because "podman alone: $(cat "$dir/podman.log")" || return 1
  out="$(env -u HI_BACKENDS HI_BE_LOG="$dir/both.log" HI_EXTRA_PACKAGES="" HI_APT_CACHE="$dir/cache" \
    GITHUB_ACTION_PATH="$_HI_ROOT/.github/actions/setup-backends" PATH="$dir/bin:$PATH" \
    bash "$_HI_ROOT/.github/actions/setup-backends/install.sh" 2>&1)" || _hi_because "the default failed: $out" || return 1
  drop="$(grep -n '^rm -f /etc/apt/sources.list.d/' "$dir/both.log" | cut -d: -f1)"
  list="$(grep -n '^tee /etc/apt/sources.list.d/hashicorp.list$' "$dir/both.log" | cut -d: -f1)"
  { [ -n "$drop" ] &&
    [ -n "$list" ] &&
    [ "$drop" -lt "$list" ] &&
    grep -qx 'curl -sSfL https://apt.releases.hashicorp.com/gpg' "$dir/both.log" &&
    grep -qx 'tee /usr/share/keyrings/hashicorp-archive-keyring.gpg' "$dir/both.log" &&
    grep -qx "apt-get -o Dir::Cache::Archives=$dir/cache install -y podman nomad" "$dir/both.log"; } || _hi_because "the default: $(cat "$dir/both.log")" || return 1
  got="$(tail -n 1 "$dir/both.log")"
  [ "$got" = "nomad version" ] || _hi_because "the default: $(cat "$dir/both.log")"
}

# _hi_bsd_loop <dir> [NAME=VALUE...] - bsd_loopback.sh in a workspace of
# stand-ins: git, timeout, and ssh-keygen log their words (the last leaving a
# key pair), and python3, the pty the client runs under, says $HI_LOOP_SAYS
# and exits $HI_LOOP_RC
function _hi_bsd_loop() {
  local dir="$1" tool
  shift
  if [ ! -d "$dir/ws" ]; then
    mkdir -p "$dir/bin" "$dir/ws/.github/scripts" "$dir/home" "$dir/tmp"
    cp "$_HI_ROOT/.github/scripts/no_hi_session_left.sh" "$dir/ws/.github/scripts/"
    for tool in git timeout; do
      # shellcheck disable=SC2016 # the stubs expand these, not this shell
      printf '#!/bin/sh\nprintf "%s %%s\\n" "$*" >>"$HI_LOOP_LOG"\n' "$tool" >"$dir/bin/$tool"
    done
    # shellcheck disable=SC2016
    {
      printf '#!/bin/sh\nmkdir -p "$HOME/.ssh"\n: >"$HOME/.ssh/loop"\necho "ssh-ed25519 LOOPKEY" >"$HOME/.ssh/loop.pub"\n' >"$dir/bin/ssh-keygen"
      printf '#!/bin/sh\nshift 2\nprintf "client %%s\\n" "$*" >>"$HI_LOOP_LOG"\necho "$HI_LOOP_SAYS"\nexit "$HI_LOOP_RC"\n' >"$dir/bin/python3"
    }
    printf '#!/bin/sh\n' >"$dir/bin/sleep"
    chmod +x "$dir/bin"/*
  fi
  env HOME="$dir/home" USER=tester GITHUB_WORKSPACE="$dir/ws" TMPDIR="$dir/tmp" HI_LOOP_LOG="$dir/log" \
    HI_LOOP_SAYS=HI_BSD_LOOP_OK HI_LOOP_RC=0 PATH="$dir/bin:$PATH" "$@" \
    bash "$_HI_ROOT/.github/scripts/bsd_loopback.sh" 2>&1
}

# bsd_loopback.sh: the fast group under a timeout, a throwaway key trusted
# for the loopback, and hi at 127.0.0.1 through it. Green takes the marker,
# a zero exit from the client, and no session directory left behind - each
# alone is not enough.
function test_bsd_loopback_wants_the_marker_a_clean_exit_and_no_session() {
  local dir="$_HI_WORKDIR/bsdloop" out rc=0
  out="$(_hi_bsd_loop "$dir")" || _hi_because "the green path failed: $out" || return 1
  grep -qx "git config --global --add safe.directory $dir/ws" "$dir/log" &&
    grep -qx 'timeout -k 30 900 bash ./tests/test_runner.sh --host-report --group fast' "$dir/log" &&
    grep -q "^client bash ./hi.sh -i $dir/home/.ssh/loop .*tester@127.0.0.1 echo HI_BSD_LOOP_OK\$" "$dir/log" &&
    grep -qx 'ssh-ed25519 LOOPKEY' "$dir/home/.ssh/authorized_keys" || _hi_because "it ran: $(cat "$dir/log")" || return 1
  out="$(_hi_bsd_loop "$dir" HI_LOOP_SAYS=nothing)" || rc=$?
  [ "$rc" -ne 0 ] || _hi_because "passed with no marker: $out" || return 1
  rc=0
  out="$(_hi_bsd_loop "$dir" HI_LOOP_RC=3)" || rc=$?
  [ "$rc" -eq 3 ] && [[ "$out" == *"hi exited 3 after a successful remote command"* ]] || _hi_because "a late failure, rc $rc: $out" || return 1
  mkdir -p "$dir/tmp/ab.hi.cd"
  rc=0
  out="$(_hi_bsd_loop "$dir")" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"session directory survived the exit"* ]] || _hi_because "a session left, rc $rc: $out"
}

# the apt helpers every installing step shares, with sudo and sleep stood in:
# the vendor lists are removed, and an update that fails is retried over a
# cleared index cache - twice, then the step fails
function test_apt_update_retries_over_a_cleared_cache() {
  local got got2 got3
  local dir="$_HI_WORKDIR/aptlib" out rc=0
  mkdir -p "$dir/bin"
  cat >"$dir/bin/sudo" <<'EOF'
#!/usr/bin/env bash
dir="${3:-}"
printf '%s\n' "$1 $2 ${dir%%/lists/*}" >>"$HI_APT_LOG"
[ "$1 $2" != "apt-get update" ] || [ "$(grep -c '^apt-get update' "$HI_APT_LOG")" -gt "$HI_APT_FAILS" ]
EOF
  # shellcheck disable=SC2016 # the stub expands these, not this shell
  printf '#!/bin/sh\nprintf "sleep %%s\\n" "$1" >>"$HI_APT_LOG"\n' >"$dir/bin/sleep"
  chmod +x "$dir/bin/sudo" "$dir/bin/sleep"
  out="$(HI_APT_LOG="$dir/once" HI_APT_FAILS=1 PATH="$dir/bin:$PATH" bash -c '
    source "$1/.github/actions/apt/lib.sh"
    _ci_apt_drop_vendor_lists && _ci_apt_update' _ "$_HI_ROOT" 2>&1)" || _hi_because "one failure was fatal: $out" || return 1
  got="$(sed -n 1p "$dir/once")"
  got2="$(sed 1d "$dir/once")"
  [[ "$got" == "rm -f /etc/apt/sources.list.d/"* ]] &&
    [ "$got2" = $'apt-get update \nrm -rf /var/lib/apt\nsleep 5\napt-get update ' ] &&
    [[ "$out" == *"(attempt 1/3), clearing the index cache"* ]] || _hi_because "one failure: $(cat "$dir/once") | $out" || return 1
  out="$(HI_APT_LOG="$dir/never" HI_APT_FAILS=9 PATH="$dir/bin:$PATH" bash -c '
    source "$1/.github/actions/apt/lib.sh"
    _ci_apt_update' _ "$_HI_ROOT" 2>&1)" || rc=$?
  got="$(grep -c '^apt-get update' "$dir/never")"
  got2="$(grep -c '^rm -rf' "$dir/never")"
  got3="$(grep '^sleep' "$dir/never" | tr '\n' ' ')"
  [ "$rc" -eq 1 ] &&
    [ "$got" -eq 3 ] &&
    [ "$got2" -eq 2 ] &&
    [ "$got3" = "sleep 5 sleep 10 " ] &&
    [[ "$out" == *"apt-get update failed three times"* ]] || _hi_because "three failures, rc $rc: $(cat "$dir/never") | $out"
}

# resolve writes the pin, its checksum, and where the binary will land; a
# version override needs a checksum of its own, and an unknown tool, a
# platform the row has no asset for, and a stray subcommand each fail by name
function test_setup_tool_resolve_names_the_pin() {
  local got2
  local dir out rc=0 a b plat
  dir="$(_hi_tool_dir resolve)"
  a="$(printf '%064d' 1)" b="$(printf '%064d' 2)"
  # shellcheck source=../../.github/actions/setup-tool/lib.sh
  plat="$(source "$_HI_ROOT/.github/actions/setup-tool/lib.sh" && _ci_platform)"
  printf '%s\n' "one|1.2.3|raw|https://x/one-%v||-||$a" "two|2.0|raw|https://x/%a||-||$plat:slug=$b" \
    "far|1|raw|https://x/%a||-||plan9-mips=$a" >"$dir/tools.txt"
  _hi_tool_run "$dir" resolve CI_TOOL=one >/dev/null || _hi_why dir || return 1
  got2="$(cat "$dir/output")"
  [ "$got2" = "version=1.2.3"$'\n'"sha256=$a"$'\n'"path=$dir/out/one" ] || _hi_because "one: $got2" || return 1
  : >"$dir/output"
  _hi_tool_run "$dir" resolve CI_TOOL=two >/dev/null && grep -qx "sha256=$b" "$dir/output" || _hi_why dir b || return 1
  : >"$dir/output"
  _hi_tool_run "$dir" resolve CI_TOOL=one CI_TOOL_VERSION=9.9 CI_TOOL_SHA256="$b" >/dev/null || _hi_because "an override: $(cat "$dir/output")" || return 1
  got2="$(cat "$dir/output")"
  [ "$got2" = "version=9.9"$'\n'"sha256=$b"$'\n'"path=$dir/out/one" ] || _hi_because "an override: $got2" || return 1
  out="$(_hi_tool_run "$dir" resolve CI_TOOL=one CI_TOOL_VERSION=9.9)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"one version 9.9 overrides the pin (1.2.3) without a sha256"* ]] || _hi_because "a bare override: $out" || return 1
  rc=0
  out="$(_hi_tool_run "$dir" resolve CI_TOOL=nope)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"no row for 'nope'"* ]] || _hi_because "an unknown tool: $out" || return 1
  rc=0
  out="$(_hi_tool_run "$dir" resolve CI_TOOL=far)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"far cannot be installed on $plat"* ]] || _hi_because "a foreign platform: $out" || return 1
  rc=0
  out="$(_hi_tool_run "$dir" fetch CI_TOOL=one)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"expected 'resolve' or 'install', got 'fetch'"* ]] || _hi_why rc out
}

# install, for a bare executable: fetched from the url with the pin and the
# platform's slug filled in, checked against the row's sha256, made
# executable, and run with the row's verify flags; bytes that do not match
# are refused and nothing lands
function test_setup_tool_installs_a_verified_binary() {
  local got2 got3
  local dir out rc=0 plat
  dir="$(_hi_tool_dir raw)"
  # shellcheck source=../../.github/actions/setup-tool/lib.sh
  plat="$(source "$_HI_ROOT/.github/actions/setup-tool/lib.sh" && _ci_platform)"
  # shellcheck disable=SC2016 # the installed tool expands these
  printf '#!/bin/sh\necho "ran $*"\n' >"$dir/src/one-1.2.3-slug"
  printf 'something else\n' >"$dir/src/bad-1"
  printf '%s\n' "one|1.2.3|raw|https://x/dl/v%v/one-%v-%a|--version -q|-||$plat:slug=$(_hi_tool_sum "$dir/src/one-1.2.3-slug")" \
    "bad|1|raw|https://x/bad-%v||-||$(printf '%064d' 1)" >"$dir/tools.txt"
  out="$(_hi_tool_run "$dir" install CI_TOOL=one)" || _hi_because "the install failed: $out" || return 1
  got2="$(cat "$dir/urls")"
  [ "$out" = "ran --version -q" ] && [ -x "$dir/out/one" ] && [ "$got2" = "https://x/dl/v1.2.3/one-1.2.3-slug" ] || _hi_because "said [$out], asked for $got2" || return 1
  out="$(_hi_tool_run "$dir" install CI_TOOL=bad)" || rc=$?
  got2="$(printf '%064d' 1)"
  got3="$(_hi_tool_sum "$dir/src/bad-1")"
  [ "$rc" -eq 1 ] && [[ "$out" == *"bad@1 checksum mismatch for https://x/bad-1 - expected $got2, got $got3"* ]] && [ ! -e "$dir/out/bad" ] || _hi_because "a mismatch, rc $rc: $out"
}

# an archive is unpacked whole and searched for the tool by name: inside a
# versioned directory, or as this machine's among one build per arch; two
# that no arch tells apart are refused rather than one taken
function test_setup_tool_finds_the_binary_inside_an_archive() {
  local dir out rc=0 stage arch
  dir="$(_hi_tool_dir tar)"
  arch="$(uname -m)"
  stage="$dir/stage"
  mkdir -p "$stage/deep/tool-1.0/bin" "$stage/arch/$arch" "$stage/arch/other-cpu" "$stage/twins/a" "$stage/twins/b"
  printf '#!/bin/sh\necho deep\n' >"$stage/deep/tool-1.0/bin/deep"
  printf 'not the tool\n' >"$stage/deep/tool-1.0/deep.1"
  printf '#!/bin/sh\necho mine\n' >"$stage/arch/$arch/arch"
  printf '#!/bin/sh\necho theirs\n' >"$stage/arch/other-cpu/arch"
  printf '#!/bin/sh\n' >"$stage/twins/a/twins"
  printf '#!/bin/sh\n' >"$stage/twins/b/twins"
  chmod +x "$stage/deep/tool-1.0/bin/deep" "$stage/arch"/*/arch "$stage/twins"/*/twins
  for out in deep arch twins; do tar -czf "$dir/src/$out.tar.gz" -C "$stage/$out" . || _hi_why dir out stage || return 1; done
  printf '%s\n' "deep|1.0|tar.gz|https://x/deep.tar.gz||-||$(_hi_tool_sum "$dir/src/deep.tar.gz")" \
    "arch|1.0|tar.gz|https://x/arch.tar.gz||-||$(_hi_tool_sum "$dir/src/arch.tar.gz")" \
    "twins|1.0|tar.gz|https://x/twins.tar.gz||-||$(_hi_tool_sum "$dir/src/twins.tar.gz")" >"$dir/tools.txt"
  out="$(_hi_tool_run "$dir" install CI_TOOL=deep)" && [ "$out" = deep ] || _hi_because "a versioned directory: $out" || return 1
  out="$(_hi_tool_run "$dir" install CI_TOOL=arch)" && [ "$out" = mine ] || _hi_because "one build per arch: $out" || return 1
  out="$(_hi_tool_run "$dir" install CI_TOOL=twins)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"no single "*" executable named twins inside https://x/twins.tar.gz"* ]] &&
    [ ! -e "$dir/out/twins" ] || _hi_because "two candidates, rc $rc: $out"
}

# %a in a url and a per-platform sha256 come as a pair, and a kind nobody
# wrote an arm for is refused: each before anything is fetched
function test_setup_tool_refuses_a_row_that_cannot_work() {
  local dir out rc=0 a plat
  dir="$(_hi_tool_dir rows)"
  a="$(printf '%064d' 1)"
  # shellcheck source=../../.github/actions/setup-tool/lib.sh
  plat="$(source "$_HI_ROOT/.github/actions/setup-tool/lib.sh" && _ci_platform)"
  printf '%s\n' "slugless|1|raw|https://x/%a||-||$a" "urlless|1|raw|https://x/u||-||$plat=$a" \
    "odd|1|deb|https://x/odd||-||$a" >"$dir/tools.txt"
  out="$(_hi_tool_run "$dir" install CI_TOOL=slugless)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"slugless's url has %a but its sha256 is a single hex"* ]] || _hi_because "no slug: $out" || return 1
  rc=0
  out="$(_hi_tool_run "$dir" install CI_TOOL=urlless)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"urlless's sha256 lists platforms but its url has no %a"* ]] || _hi_because "no %a: $out" || return 1
  rc=0
  out="$(_hi_tool_run "$dir" install CI_TOOL=odd)" || rc=$?
  [ "$rc" -eq 1 ] && [[ "$out" == *"unknown kind 'deb' for odd"* ]] && [ ! -e "$dir/urls" ] || _hi_because "an unknown kind: $out"
}

# setup-tools, the batch over the same installer: resolve folds every tool
# into one cache key (name, pin, the checksum's first twelve digits) and one
# path list, and the install step fetches only what the cache did not restore
function test_setup_tools_batches_resolve_and_install() {
  local dir out sum got got2 got3
  dir="$(_hi_tool_dir batch)"
  printf '#!/bin/sh\necho one\n' >"$dir/src/one"
  printf '#!/bin/sh\necho two\n' >"$dir/src/two"
  sum="$(_hi_tool_sum "$dir/src/two")"
  printf '%s\n' "one|1.0|raw|https://x/one||-||$(_hi_tool_sum "$dir/src/one")" "two|2.5|raw|https://x/two||-||$sum" >"$dir/tools.txt"
  env -u CI_TOOL_VERSION -u CI_TOOL_SHA256 CI_TOOLS="one two" CI_TOOLS_TXT="$dir/tools.txt" CI_TOOL_BIN_DIR="$dir/out" \
    GITHUB_OUTPUT="$dir/output" bash "$_HI_ROOT/.github/actions/setup-tools/resolve.sh" || _hi_why dir || return 1
  out="$(cat "$dir/output")"
  got="$(_hi_tool_sum "$dir/src/one" | cut -c1-12)"
  [ "$out" = "key= one=1.0@$got two=2.5@${sum:0:12}"$'\n'"paths<<CI_TOOLS_EOF"$'\n'"$dir/out/one"$'\n'"$dir/out/two"$'\n'"CI_TOOLS_EOF" ] ||
    _hi_because "the outputs: $out" || return 1
  printf '#!/bin/sh\necho restored\n' >"$dir/out/one"
  chmod +x "$dir/out/one"
  out="$(env -u CI_TOOL_VERSION -u CI_TOOL_SHA256 CI_TOOLS="one two" CI_TOOLS_TXT="$dir/tools.txt" CI_TOOL_BIN_DIR="$dir/out" \
    HI_TOOL_SRC="$dir/src" PATH="$dir/bin:$PATH" bash "$_HI_ROOT/.github/actions/setup-tools/install-missing.sh" 2>&1)" ||
    _hi_because "the batch install failed: $out" || return 1
  got="$("$dir/out/one")"
  got2="$("$dir/out/two")"
  got3="$(cat "$dir/urls")"
  [ "$got" = restored ] && [ "$got2" = two ] && [ "$got3" = "https://x/two" ] ||
    _hi_because "fetched: $got3"
}

# A release asset name may not begin with a dot: GitHub stores `.SRCINFO` as
# `default.SRCINFO`, so publish-external.yml's `--pattern .SRCINFO` matched
# nothing and the failure surfaced two steps later, at the cp. The manifest
# travels as `SRCINFO` and gets its dot back at the AUR checkout, and the
# name release.yml collects, the pattern publish-external.yml asks for, and
# the file it copies are one string.
function test_srcinfo_travels_under_a_dotless_asset_name() {
  [ -f "$_HI_PUBLISH_EXTERNAL_WF" ] || return 0
  { grep -qF 'cp packaging/aur/say-hi/.SRCINFO dist/manifests/SRCINFO' "$_HI_RELEASE_WF" &&
    grep -qF -- '--pattern PKGBUILD --pattern SRCINFO' "$_HI_PUBLISH_EXTERNAL_WF" &&
    grep -qF 'cp dist/manifests/SRCINFO aur/.SRCINFO' "$_HI_PUBLISH_EXTERNAL_WF" &&
    ! grep -qE 'dist/manifests/\.' "$_HI_RELEASE_WF" "$_HI_PUBLISH_EXTERNAL_WF"; } || _hi_why _HI_RELEASE_WF _HI_PUBLISH_EXTERNAL_WF
}

# each job's manifest comes off the release itself, never a same-run build
# artifact - the whole point of decoupling this from release.yml's build/
# publish jobs is that it can run any time after a tag has published
function test_publish_external_reads_manifests_from_the_release() {
  [ -f "$_HI_PUBLISH_EXTERNAL_WF" ] || return 0
  { grep -qF 'gh release download' "$_HI_PUBLISH_EXTERNAL_WF" &&
    ! grep -q 'download-artifact' "$_HI_PUBLISH_EXTERNAL_WF"; } || _hi_why _HI_PUBLISH_EXTERNAL_WF
}

# The workflows and composite actions every structural check below reads.
function _hi_wf_files() {
  local f
  for f in "$_HI_ROOT"/.github/workflows/*.yml "$_HI_ROOT"/.github/actions/*/action.yml; do
    [ -f "$f" ] && printf '%s\n' "$f"
  done
}

# _hi_wf_steps_missing <file> <hit-awk-cond> <ok-awk-cond> - the line number
# of every step with a line matching the first condition and none matching the
# second.
# A step runs from its `- key:` line to the next line indented no deeper than
# that dash (comments aside), which covers both `- uses:` and `- name:` then
# `uses:` step shapes.
function _hi_wf_steps_missing() {
  awk '
    function indent(s,    i) { i = 0; while (substr(s, i + 1, 1) == " ") i++; return i }
    function flush() {
      if (open && hit && !ok) print start
      open = 0; hit = 0; ok = 0
    }
    /^[ \t]*$/ || /^[ \t]*#/ { next }
    open && indent($0) <= ind { flush() }
    /^ *- [A-Za-z-]+:/ { flush(); open = 1; ind = indent($0); start = NR }
    open && ('"$2"') { hit = 1 }
    open && ('"$3"') { ok = 1 }
    END { flush() }
  ' "$1"
}

# every job carries timeout-minutes: a hung step otherwise holds a runner for
# GitHub's 6-hour default. A job that calls a reusable workflow (`uses:` at
# job level) takes no timeout of its own - the callee's jobs carry theirs.
function test_every_job_has_a_timeout() {
  local wf job bad=0
  for wf in "$_HI_ROOT"/.github/workflows/*.yml; do
    while IFS= read -r job; do
      _hi_cecho " | ${wf##*/}: job $job has no timeout-minutes" "$RED"
      bad=1
    done < <(awk "$_HI_WF_JOBS_AWK"'
      function flush() { if (job != "" && !has) print job; job = ""; has = 0 }
      isjob() { flush(); job = jobname(); next }
      /^    (timeout-minutes|uses):/ { has = 1 }
      END { flush() }
    ' "$wf")
  done
  [ "$bad" = 0 ] || _hi_why bad
}

# every job's first step is harden-runner, so its egress is recorded (audit)
# or allowlisted (block) from before anything else runs. Exempt: a job that
# calls a reusable workflow (no steps - the callee's jobs carry it), and an
# arm runner (`*-arm`), which harden-runner's community tier does not
# support. A matrix `runs-on` counts as supported: its x64 legs are monitored
# and an arm leg only logs that it is not.
function test_every_job_starts_with_harden_runner() {
  local wf job bad=0
  for wf in "$_HI_ROOT"/.github/workflows/*.yml; do
    while IFS= read -r job; do
      _hi_cecho " | ${wf##*/}: job $job does not start with step-security/harden-runner" "$RED"
      bad=1
    done < <(awk "$_HI_WF_JOBS_AWK"'
      function flush() {
        if (job != "" && steps && !arm && !ok) print job
        job = ""; steps = 0; arm = 0; ok = 0; first = 0; done = 0
      }
      isjob() { flush(); job = jobname(); next }
      /^    runs-on:.*-arm/ { arm = 1 }
      /^    steps:/ { steps = 1; next }
      !steps || done || /^[ \t]*(#.*)?$/ { next }
      /^      - / { if (first) { done = 1; next } first = 1 }
      /^    [A-Za-z]/ { done = 1; next }
      first && /uses:[ \t]*step-security\/harden-runner@/ { ok = 1 }
      END { flush() }
    ' "$wf")
  done
  [ "$bad" = 0 ] || _hi_why bad
}

# every actions/checkout sets persist-credentials: false, so no later step
# (or a compromised action) can read the job token back out of .git/config
function test_every_checkout_drops_its_credentials() {
  local f line bad=0
  while IFS= read -r f; do
    while IFS= read -r line; do
      [ -n "$line" ] || continue
      _hi_cecho " | ${f#"$_HI_ROOT/"}:$line checks out without persist-credentials: false" "$RED"
      bad=1
    done < <(_hi_wf_steps_missing "$f" '/uses:[ \t]*actions\/checkout@/' '/persist-credentials:[ \t]*false/')
  done < <(_hi_wf_files)
  [ "$bad" = 0 ] || _hi_why bad
}

# every third-party `uses:` is a 40-hex commit SHA with its full `# vX.Y.Z`
# beside it: a tag can be moved under a pin, and the comment is what dependabot
# rewrites and check_tool_versions.sh reads. `$/` and `./` are this repo's own.
function test_every_third_party_action_is_sha_pinned() {
  local f out line bad=0
  while IFS= read -r f; do
    out="$(grep -nE '^[^#]*uses:[[:space:]]*[^[:space:]]' "$f" |
      grep -vE 'uses:[[:space:]]*["'"'"']?(\$/|\./)' |
      grep -vE 'uses:[[:space:]]*[^[:space:]@]+@[0-9a-f]{40}[[:space:]]+#[[:space:]]*v[0-9]+\.[0-9]+\.[0-9]+([[:space:]]|$)' || true)"
    [ -n "$out" ] || continue
    while IFS= read -r line; do
      _hi_cecho " | ${f#"$_HI_ROOT/"}:${line%%:*} is not a SHA pin with a full # vX.Y.Z comment" "$RED"
      bad=1
    done <<<"$out"
  done < <(_hi_wf_files)
  [ "$bad" = 0 ] || _hi_why bad
}

# every workflow_run workflow reads the triggering run's conclusion: the
# trigger fires on `completed`, red runs included, so a missing gate is a job
# running off a failed battery (test_ci_chained_workflows_carry_the_green_push_gate
# adds the push half for those chained off CI)
function test_workflow_run_workflows_gate_on_success() {
  local wf bad=0
  for wf in "$_HI_ROOT"/.github/workflows/*.yml; do
    grep -qE '^  workflow_run:' "$wf" || continue
    grep -qF "workflow_run.conclusion == 'success'" "$wf" || {
      _hi_cecho " | ${wf##*/} triggers on workflow_run without a conclusion == 'success' gate" "$RED"
      bad=1
    }
  done
  [ "$bad" = 0 ] || _hi_why bad
}

# fetch-latest-artifact scopes its lookup to the producer's trigger, default
# push, because a fork PR's run on a branch named main otherwise passes
# `branch: main`; `event: ""` (any trigger) is only safe for a producer with
# no pull_request trigger at all
function test_fetch_latest_artifact_scopes_the_event() {
  local action="$_HI_ROOT/.github/actions/fetch-latest-artifact/action.yml" wf producer bad=0
  # shellcheck disable=SC2016 # the action's own literal, expanded there
  grep -qF 'event=$EVENT' "$action" || _hi_why action || return 1
  awk '/^  event:/ { e = 1 } e && /default: "push"/ { found = 1 } END { exit !found }' "$action" || _hi_why action || return 1
  for wf in "$_HI_ROOT"/.github/workflows/*.yml; do
    while IFS= read -r producer; do
      [ -n "$producer" ] || continue
      ! grep -qE '^  pull_request(_target)?:' "$_HI_ROOT/.github/workflows/$producer" || {
        _hi_cecho " | ${wf##*/} reads $producer's artifacts from any event, and $producer runs on pull_request" "$RED"
        bad=1
      }
    done < <(awk '
      function indent(s,    i) { i = 0; while (substr(s, i + 1, 1) == " ") i++; return i }
      function flush() { if (open && any) print producer; open = 0; any = 0; producer = "" }
      /^[ \t]*$/ || /^[ \t]*#/ { next }
      open && indent($0) <= ind { flush() }
      /^ *- [A-Za-z-]+:/ { flush(); ind = indent($0) }
      /uses:[ \t]*\$\/\.github\/actions\/fetch-latest-artifact/ { open = 1 }
      open && /^ *workflow:/ { producer = $2 }
      open && /^ *event:[ \t]*(""|'"''"')?[ \t]*$/ { any = 1 }
      END { flush() }
    ' "$wf")
  done
  [ "$bad" = 0 ] || _hi_why bad
}

# ...and takes the newest green run that still holds a matching artifact, not
# simply the newest green run: a run whose producing job skipped is green with
# nothing to download, and would hide the real one behind a grey badge. The
# brace pattern every multi-artifact caller passes is matched per name, as an
# extglob.
# shellcheck disable=SC2016 # the action's own literals, expanded there
function test_fetch_latest_artifact_skips_runs_without_the_artifact() {
  local action="$_HI_ROOT/.github/actions/fetch-latest-artifact/action.yml"
  { grep -qF 'status=success&per_page=20' "$action" &&
    grep -qF 'actions/runs/$id/artifacts' "$action" &&
    grep -qF 'select(.expired | not)' "$action" &&
    grep -qF 'shopt -s extglob' "$action" &&
    grep -qF 'pattern: ${{ inputs.artifact-name }}' "$action"; } || _hi_why action
}

function run_packaging_ci_workflows_tests() {
  _hi_packaging_ci_begin

  _hi_h1 "Testing packaging/ (ci) (workflows)"

  _hi_h2 "Testing: every workflow and composite action"
  _hi_check "Every job has timeout-minutes" test_every_job_has_a_timeout
  _hi_check "Every job starts with harden-runner" test_every_job_starts_with_harden_runner
  _hi_check "Every checkout sets persist-credentials: false" test_every_checkout_drops_its_credentials
  _hi_check "Every third-party action is a SHA with a # vX.Y.Z" test_every_third_party_action_is_sha_pinned
  _hi_check "Every workflow_run workflow gates on success" test_workflow_run_workflows_gate_on_success
  _hi_check "fetch-latest-artifact scopes its lookup to an event" test_fetch_latest_artifact_scopes_the_event
  _hi_check "...and skips a green run with no matching artifact" test_fetch_latest_artifact_skips_runs_without_the_artifact

  _hi_h2 "Testing: publish-external.yml"
  _hi_check "aur is dispatch-only, not in release.yml" test_aur_is_dispatch_only
  _hi_check "...and skips a prerelease tag" test_prerelease_tags_reach_no_external_channel
  _hi_check "...reading its manifest off the release" test_publish_external_reads_manifests_from_the_release
  _hi_check "release.yml opens the tap PR after brew passes" test_release_workflow_opens_the_tap_pr_after_brew
  _hi_check "tap_formula.sh swaps only the template header" test_tap_formula_swaps_only_the_template_header
  _hi_check "The release body links the tap PR and embeds the demo" test_release_body_links_the_tap_pr_and_embeds_the_demo
  _hi_check "release_slot.sh fills only its own line" test_release_slot_fills_only_its_own_line
  _hi_check "release_slot.sh writes the body back through gh" test_release_slot_writes_the_body_back_through_gh
  _hi_check "gh_asset.sh clears the name and falls back to the raw endpoint" test_gh_asset_retries_through_the_raw_endpoint
  _hi_check "...attaching the rest and naming what did not land" test_gh_asset_attaches_the_rest_and_names_the_missing
  _hi_check "SRCINFO travels under a dotless asset name" test_srcinfo_travels_under_a_dotless_asset_name

  _hi_h2 "Testing: setup-tool and setup-tools"
  _hi_check "lib.sh reads the roster and picks a platform's sha256" test_setup_tool_lib_reads_the_roster
  _hi_check "resolve names the pin, its checksum, and the path" test_setup_tool_resolve_names_the_pin
  _hi_check_capable mode_bits "install fetches, verifies, and runs a binary" test_setup_tool_installs_a_verified_binary
  _hi_check_capable mode_bits "...finding it inside an archive" test_setup_tool_finds_the_binary_inside_an_archive
  _hi_check "...and refuses a row that cannot work" test_setup_tool_refuses_a_row_that_cannot_work
  _hi_check_capable mode_bits "setup-tools batches resolve and install" test_setup_tools_batches_resolve_and_install
  _hi_check_capable mode_bits "install builds a make or cmake kind from its tarball" test_setup_tool_builds_from_a_source_tarball
  _hi_check_capable mode_bits "...assuming its build deps where there is no apt-get" test_setup_tool_assumes_build_deps_without_apt
  _hi_check_capable lockout "...and reaches for sudo only for a locked bin dir" test_setup_tool_reaches_for_sudo_only_for_a_locked_bin_dir
  _hi_check "apt's update is retried over a cleared index cache" test_apt_update_retries_over_a_cleared_cache
  _hi_check "setup-backends adds HashiCorp's repository only for nomad" test_setup_backends_adds_hashicorp_only_for_nomad
  _hi_check "bsd_loopback.sh wants the marker, a clean exit, and no session" test_bsd_loopback_wants_the_marker_a_clean_exit_and_no_session

  _hi_suite_end "packaging (ci) (workflows)"
}

run_packaging_ci_workflows_tests
