#!/usr/bin/env bash
# Copyright the say-hi contributors.
# SPDX-License-Identifier: MIT
# tap_formula.sh <formula >tap-formula - the formula as the Homebrew tap
# carries it. packaging/homebrew/say-hi.rb opens with a header written for
# this repository (a v0.0.0 template, don't run bump.sh on it) that is wrong
# once the file sits in the tap, so release.yml's tap job swaps it: every
# line above the first bare `#` becomes the three lines below, and the rest -
# that `#` and the class_s comment under it included - passes through
# untouched. A formula with no bare `#` before `class` fails rather than
# losing its class line. tests/packaging/packaging_test.sh drives it against
# the committed template.
set -euo pipefail

[ $# -eq 0 ] || {
  echo "usage: tap_formula.sh <formula >tap-formula" >&2
  exit 2
}

awk '
  !done && $0 == "#" {
    print "# Generated by say-hi'\''s release workflow from packaging/homebrew/say-hi.rb"
    print "# in https://github.com/ivylikethevine/say-hi. Edit it there, not here."
    print "# Pull requests to this tap are opened automatically for each release."
    done = 1
  }
  !done && /^class / { exit 1 }
  done { print }
  END { if (!done) exit 1 }
' || {
  echo "tap_formula.sh: no bare '#' line ends the template header" >&2
  exit 1
}
